### PR TITLE
add output has_new_commits

### PR DESCRIPTION
**Pull request by cognifloyd**
Adds #3 

What do you think?

### CODE REVIEW

**Comment by aormsby** [comment]
I agree, this would be a nice output to have. However, I'm not comfortable tying it to the log message since that could change at any time. I'd rather have the output come from a (new) var in the shell script that gets set after the pull step (or even after the push is complete). More stable long term.

Maybe we'd `export` the var value out to the environment and then set the output using that in the js. Not sure offhand if this works. Thoughts?

**Comment by cognifloyd** [comment]
Ah ha. Apparently, github actions already have the ability to do this via stdout:
https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter

I adjusted this PR to follow that convention instead.

**Comment by aormsby** [comment]
Haha, I was just reading the same thing. I think this is much better.

Food for thought - why put the 'true' command where you chose to? Why not after the actual pull occurs (or even the push) where things could still potentially fail? Wouldn't you want to know that the action completed successfully with the new commits - instead of just knowing there are new commits and not knowing if they came through alright?

**Comment by cognifloyd** [comment]
If you'd prefer, I can move it to the end.

I figure that if there's an error, then the workflow won't proceed to the next step without explicit handling in `if`.
So, you have two pieces of info: success/failure and has_new_commits.
A workflow could, for example, when the sync step fails and has_new_commits is true, create a PR. If has_new_commits is not defined, then it would have failed during the checkout or fetch stages, which would require different steps to remediate the issue.

**Comment by cognifloyd** [comment]
Links to docs:
Use `continue-on-error` on the sync step (for example with `id: sync`)
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error
In the next step do `if: steps.sync.conclusion == 'failure' and steps.sync.outputs.has_new_commits == 'true'` to handle when there is a failure and there are new commits.

**Comment by aormsby** [comment]
Okay yeah, your placement makes more sense now. I was unaware that a job stopped if a step failed (knowing different jobs themselves run in parallel). Thanks for the doc links, very helpful for my own edification.

Testing and merging. 🙂

**Comment by aormsby** [comment]
Done and tagged at **v1.1**. Thanks!

**Pull request merged**
