### PR TITLE
Fix output was not set if fetching from upstream resulted in error

### PR DESCRIPTION
**Pull request by Fubuchi**

### CODE REVIEW

**Comment by aormsby** [comment]
Was this causing an issue? I remember all my tests going fine when I didn't explicitly the output to false. Probably a good fix, just want to understand your use case.

**Comment by Fubuchi** [comment]
If the output value is empty, then both check `output == 'true'` and `output == 'false'` are false in subsequent steps or jobs

Without the fix

image

 With the fix

image

https://github.com/Fubuchi/clr-boot-manager/blob/846892eee9/.github/workflows/main.yml#L58

**Comment by aormsby** [comment]
Sweet, thanks for sharing. I'll merge this. 👍 

I'm waiting on another issue fix to be confirmed right now. I think I'll put them together in the same release. Shouldn't be too long.

**Comment by aormsby** [comment]
Pre-released to `v3.3`!

**Pull request merged**
